openapi: 3.0.0
info:
  title: Tech Stack API
  description: API for managing technology stack information
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Development server
paths:
  /tech-stack:
    get:
      summary: Get all technology stack data
      responses:
        '200':
          description: Technology stack data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TechStackData'
    post:
      summary: Create technology stack data
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TechStackData'
      responses:
        '201':
          description: Technology stack data created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TechStackData'
  /tech-stack/categories:
    get:
      summary: Get technology categories
      responses:
        '200':
          description: Technology categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TechCategory'
  /tech-stack/recommendations:
    get:
      summary: Get technology recommendations
      parameters:
        - name: current
          in: query
          required: false
          schema:
            type: string
        - name: type
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Technology recommendations
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TechRecommendation'
  /tech-stack/compatibility:
    get:
      summary: Check technology compatibility
      parameters:
        - name: technologies
          in: query
          required: true
          schema:
            type: array
            items:
              type: string
      responses:
        '200':
          description: Compatibility analysis
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompatibilityAnalysis'
components:
  schemas:
    TechStackData:
      type: object
      properties:
        frontend:
          type: array
          items:
            $ref: '#/components/schemas/Technology'
        backend:
          type: array
          items:
            $ref: '#/components/schemas/Technology'
        database:
          type: array
          items:
            $ref: '#/components/schemas/Technology'
        deployment:
          type: array
          items:
            $ref: '#/components/schemas/Technology'
        aiTools:
          type: array
          items:
            $ref: '#/components/schemas/Technology'
        other:
          type: array
          items:
            $ref: '#/components/schemas/Technology'
    Technology:
      type: object
      properties:
        name:
          type: string
        version:
          type: string
        category:
          type: string
        description:
          type: string
        website:
          type: string
        documentation:
          type: string
        popularity:
          type: number
        compatibility:
          type: array
          items:
            type: string
    TechCategory:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        technologies:
          type: array
          items:
            $ref: '#/components/schemas/Technology'
    TechRecommendation:
      type: object
      properties:
        technology:
          type: string
        reason:
          type: string
        compatibility:
          type: number
        popularity:
          type: number
        learningCurve:
          type: string
    CompatibilityAnalysis:
      type: object
      properties:
        compatible:
          type: boolean
        issues:
          type: array
          items:
            type: string
        recommendations:
          type: array
          items:
            type: string
        score:
          type: number
